### PR TITLE
Fix JavaFX version and FilterCommand date

### LINKED ISSUE #241: [PE-D][Tester D] filter meeting date cannot tell wrong date
command: filter m/2030-80-80
**expected**
wrong date
**actual**
Filtered patients by m: 2030-80-80

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: liy722/ped#7

### LINKED ISSUE #258: [PE-D][Tester A] Wrong JavaFX API version used
Whenever I start up the program, I encountered this error:

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: FabianHeng/ped#10

### LINKED ISSUE #270: [PE-D][Tester B] Filter - did not catch constraints of out of range date for filter function
-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: davidfoo07/ped#8

### LINKED ISSUE #290: Fix JavaFX version issue

### PR DESCRIPTION
**Pull request by NoahKoh**
Resolves #241 
Resolves #258 
Resolves #270 
Resolves #290

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/FilterCommandParser.java [hunk 1]
```diff
@@ -68,9 +69,9 @@ public FilterCommand parse(String args) throws ParseException {
             break;
 
         case "m":
-            if (!value.matches("\\d{4}-\\d{2}-\\d{2}")) {
+            if (!MeetingDate.isValidMeetingDate(value)) {
                 throw new ParseException("Invalid meeting date format: '" + value + "'.\n"
-                        + "Expected format: YYYY-MM-DD");
+                        + "Expected format: YYYY-MM-DD and date must be valid");
```
Comment (zacklow28) [inline src/main/java/seedu/address/logic/parser/FilterCommandParser.java:74]: i realise, this seem to be differen error message from the date one? Can we stick to the same?

File: src/main/resources/view/MainWindow.fxml [hunk 2]
```diff
@@ -13,7 +13,7 @@
 <?import javafx.scene.layout.VBox?>
 <?import javafx.stage.Stage?>
 
-<fx:root minHeight="200" minWidth="200" onCloseRequest="#handleExit" title="VitaBook" type="javafx.stage.Stage" xmlns="http://javafx.com/javafx/23.0.1" xmlns:fx="http://javafx.com/fxml/1">
+<fx:root minHeight="600" minWidth="450" onCloseRequest="#handleExit" title="VitaBook" type="javafx.stage.Stage" xmlns="http://javafx.com/javafx/17" xmlns:fx="http://javafx.com/fxml/1">
```
Comment (zacklow28) [inline src/main/resources/view/MainWindow.fxml:16]: this one stick to the old one, or else later cannot resize
