### PR TITLE
Fix toString and format

### LINKED ISSUE #132: Person's toString never include remark

### LINKED ISSUE #133: Messages format never include remark

### PR DESCRIPTION
**Pull request by NoahKoh**
Resolves #132
Resolves #133

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Person.java [hunk 1]
```diff
@@ -166,6 +166,7 @@ public String toString() {
                 .add("diet", diet)
                 .add("priority", priority)
                 .add("meetingDate", meetingDate)
+                .add("remark", remark)
```
Comment (zacklow28) [inline src/main/java/seedu/address/model/person/Person.java:169]: Good catch!

File: src/main/java/seedu/address/logic/Messages.java [hunk 2]
```diff
@@ -56,6 +56,8 @@ public static String format(Person person) {
                 .append(person.getPriority())
                 .append("; MeetingDate: ")
                 .append(person.getMeetingDate())
+                .append("; Remark: ")
+                .append(person.getRemark())
```
Comment (zacklow28) [inline src/main/java/seedu/address/logic/Messages.java:60]: Yup, would be good to include that in the tostring method
